version: '3.7'

services:

    haproxy:
        image: haproxy:3.0.9
        container_name: 'circthread-haproxy'
        ports:
            - '8080:8080'   # forwarded to circthread-connector
            - '8090:8090'   # forwarded to circthread-app4edi
        volumes:
            - './haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'
            - './haproxy-cert.pem:/usr/local/etc/haproxy/server.pem'
        logging:
            driver: "local"
            options:
                max-size: "50m"
                max-file: "5"
        restart: always
        stop_grace_period: 30s
        networks:
            - circthread
        
    postgres:
        image: postgres:14.17
        container_name: 'postgres'
        shm_size: '128mb'
        environment:
            - 'PGPORT=5433'
            - 'POSTGRES_USER=postgres'
            - 'POSTGRES_PASSWORD_FILE=/run/secrets/postgres.properties'
            - 'POSTGRES_DB=postgres'
        secrets:
            - postgres.properties
        networks:
            - circthread
        volumes:
            - './postgres-data:/var/lib/postgresql/data'
            - './postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh'
        command: postgres -c 'max_connections=300' -c 'shared_buffers=128MB'
        logging:
            driver: "local"
            options:
                max-size: "50m"
                max-file: "5"
        restart: always
        stop_grace_period: 30s
        
    circthread-connector:
        image: docker-registry.inesctec.pt/ids/dataspace-app-4edi/dataspace-connector:8.0
        container_name: 'circthread-connector'
        environment:
            - 'SPRING_CLOUD_CONFIG_ENABLED=true'
            - 'SPRING_CLOUD_CONFIG_USERNAME=user'
            - 'SPRING_CLOUD_CONFIG_PASSWORD=pass'
            - 'SPRING_PROFILES_ACTIVE=default,circthread'
            - 'SPRING_CONFIG_IMPORT=configserver:https://vcese19.inesctec.pt:8443?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100,file:/run/secrets/circthread-connector.properties'
        secrets:
            - circthread-connector.properties
        volumes:
            - './connector-conf:/tmp/conf'
        networks:
            - circthread
        depends_on:
            - postgres
        logging:
            driver: "local"
            options:
                max-size: "50m"
                max-file: "5"
        restart: always
        stop_grace_period: 30s

    circthread-app4edi:
        image: docker-registry.inesctec.pt/ids/dataspace-app-4edi/dataspace-app-4edi:1.17
        container_name: 'circthread-app4edi'
        environment:
            - 'SPRING_CLOUD_CONFIG_ENABLED=true
            - 'SPRING_CLOUD_CONFIG_USERNAME=user
            - 'SPRING_CLOUD_CONFIG_PASSWORD=pass
            - 'SPRING_PROFILES_ACTIVE=default,circthread
            - 'SPRING_CONFIG_IMPORT=configserver:https://vcese19.inesctec.pt:8443?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100,file:/run/secrets/circthread-app4edi.properties'
        secrets:
            - circthread-app4edi.properties
        volumes:
            - './app4edi-conf:/tmp/conf'
            - './app4edi-edi-artifacts:/tmp/edi-artifacts'
            - './app4edi-data-published:/tmp/data-published'
        networks:
            - circthread
        depends_on:
            - circthread-connector
            - postgres
        logging:
            driver: "local"
            options:
                max-size: "50m"
                max-file: "5"
        restart: always
        stop_grace_period: 30s

secrets:
    postgres.properties:
        file: ./postgres.properties
    circthread-connector.properties:
        file: ./circthread-connector.properties
    circthread-app4edi.properties:
        file: ./circthread-app4edi.properties

networks:
    circthread:
